.TH "MANPAGE" "1" "September 2014" "manpage 0.0.12" "User Commands"
.SH "NAME"
manpage
.SH "USAGE"

.SP
cli\-manpage <command> [\-se] [\-\-color|\-\-no\-color]
.br
            [\-s|\-\-standalone] [\-e|\-\-error] [\-\-help] [\-\-version]
.br
            [\-o|\-\-output==<dir>] [\-a|\-\-argument==<name>]
.br
            [\-\-section==<1\-8>] <args>
.SH "DESCRIPTION"
.PP
Man page generation tool.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBhelp\fR: Show help for commands.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-o, \-\-output==[dir]\fR: Output directory for generated man pages.
.IP "\[ci]" 4
\fB\-s, \-\-standalone\fR: Generate a single standalone man page.
.IP "\[ci]" 4
\fB\-e, \-\-error\fR: Use the program stderr stream.
.IP "\[ci]" 4
\fB\-a, \-\-argument==[name]\fR: Argument used to print help output.
.IP "\[ci]" 4
\fB\-\-[no]\-color\fR: Enable or disable terminal colors.
.IP "\[ci]" 4
\fB\-\-section==[1\-8]\fR: Man page section.
.IP "\[ci]" 4
\fB\-\-help\fR: Display this help and exit.
.IP "\[ci]" 4
\fB\-\-version\fR: Output version information and exit.
.EL
.SH "BUGS"
.PP
Report bugs to muji noop@xpm.io.
